### PR TITLE
Set docker network name to bitwarden_network

### PR DESCRIPTION
**Pull request by c4539**
related to bitwarden/core#347

### CODE REVIEW

**Comment by kspearrin** [comment]
What version of compose requires 3.5? I worry about breaking existing users who may not have updated.

**Comment by kspearrin** [comment]
Also, shouldn't a user just do this with the override file?

**Comment by c4539** [comment]
3.5 has been introduced in 1.18.0 (2017-12-18).

**Comment by c4539** [comment]
@kspearrin Where can the override file be found?

**Comment by c4539** [comment]
Using the override file requires both files to have the same version, to I guess this does not for for the network name then.

**Comment by kspearrin** [comment]
For next version I added the ability specify the compose file version from the new `bwdata/config.yml`. See https://github.com/bitwarden/core/commit/477d6651043ec9a4b9b43e35b84beb21572d318e

**Pull request closed without merging**
