### PR TITLE
Update service user group

### PR DESCRIPTION
**Pull request by Mart124**
Hi,

This PR correctly sets the service user group when the user already exists.

Thank you !

### CODE REVIEW

**Comment by Mart124** [comment]
This is mainly a sanity modification : when the service user does not exist, it is added with the correct group : `useradd -g $GROUPNAME`.
However, when the service user already exists, its group was not correctly modified.
This PR then corrects this thanks to : `-g $GROUPNAME` given to `usermod`.

**Comment by kspearrin** [comment]
This seems good, though there is another docker file in the web project that probably needs this update too. I cannot merge these changes right now since it would result in a production release (these scripts are pulled from GitHub).

**Comment by Mart124** [comment]
Thank you for your feedback @kspearrin 👍 
Then let's then wait just before the next release to merge this, did I understood correctly ?
Thx !

**Comment by Mart124** [comment]
No more needed thanks to #292.

**Pull request closed without merging**
