### PR TITLE
StaticStore: add equivalent domains for Airbnb and Eventbrite

### PR DESCRIPTION
**Pull request by 3v1n0**

### CODE REVIEW

**Comment by kspearrin** [comment]
Thanks for the PR. Is there a verifiable list of these domains for these websites somewhere? Where did you get all these domains from?

**Comment by 3v1n0** [comment]
Airbnb domains are coming from https://www.airbnb.com/sitemaps/localized

As for eventbrite I went thought them checking the whois with some bash scripting...

**Comment by kspearrin** [comment]
Are you missing some AirBNB ones then? I count 55 on that site but only 53 in your PR here.

**Comment by 3v1n0** [comment]
Yes, since some like China (https://zh.airbnb.com) are already matched by default domain.

**Pull request merged**
