### PR TITLE
Allow several instances on same server

### PR DESCRIPTION
**Pull request by Mart124**
Hi,

This PR modifies `run.sh` script so that we can easily run several instances on the same server, each one in its own directory.

One may want to run several instances on the same server, or on a multi-users environment.
This could also certainly help developers !

For this, we need to make docker / docker-compose happy, so we need :
- each instance to have its own docker-compose projects name (handled by #313) ;
- each container to have a unique name (2 containers can't have the same name).

Thx !

### CODE REVIEW

**Comment by Mart124** [comment]
One may want to run several instances on the same server.
This could also certainly help developers !

For this, we need to make docker / docker-compose happy, so we need :
- each instance to have its own docker-compose projects name (thus will close #266) ;
- each container to have a uniq name (2 containers can't have the same name).

Of course, migrating to this new script in a running environment, we must take care to properly stop the current running instance which has been launched with the default project name.
This PR handles this too 👍

**Comment by kspearrin** [comment]
I am not really sure this is necessary at the moment. I don't like having to dirty up the container names for the majority of people that don't need this type of setup.

I do have some plans to re-structure all these generated files with a standard config file in the near future, so maybe we can fit this into that somehow.

**Comment by Mart124** [comment]
Perhaps we can think about a better way to make container name unique ?
Perhaps I can find a way using [environment variables](https://docs.docker.com/compose/environment-variables/) which would be set to make the containers name unique, only  if needed.
What do you think about this ?

**Comment by Mart124** [comment]
I managed to do this quite easily.
Nothing changes for the first instance launched.
The second, third etc... will have their containers name modified with a trailing `-2`, `-3` etc...
Much smaller, and nicer for servers with only one instance 👍

**Comment by Mart124** [comment]
OK, I just merged master into this, should be ready. Thx 👍

**Comment by Mart124** [comment]
Last commit allows to avoid errors like the following :
```
Migrating database.
Database is in script upgrade mode. Trying again (attempt #2)...
Migrating database.
Database is in script upgrade mode. Trying again (attempt #3)...
Migrating database.

Unhandled Exception: System.Data.SqlClient.SqlException: Login failed for user 'sa'. Reason: Server is in script upgrade mode. Only administrator can connect at this time.
   at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /Users/kyle/Projects/bitwarden/core/util/Setup/Program.cs:line 284
   at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /Users/kyle/Projects/bitwarden/core/util/Setup/Program.cs:line 280
   at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /Users/kyle/Projects/bitwarden/core/util/Setup/Program.cs:line 280
   at Bit.Setup.Program.Main(String[] args) in /Users/kyle/Projects/bitwarden/core/util/Setup/Program.cs:line 57
```

**Comment by Mart124** [comment]
Example with 2 instances running :
```
# docker ps -a
CONTAINER ID        IMAGE                          COMMAND             CREATED             STATUS              PORTS                            NAMES
38e999bf8520        bitwarden/admin:1.20.0         "/entrypoint.sh"    4 minutes ago       Up 3 minutes        5000/tcp                         bitwarden-1-admin
844e88bd405d        bitwarden/identity:1.20.0      "/entrypoint.sh"    4 minutes ago       Up 3 minutes        5000/tcp                         bitwarden-1-identity
33c1204e773d        bitwarden/api:1.20.0           "/entrypoint.sh"    4 minutes ago       Up 4 minutes        5000/tcp                         bitwarden-1-api
67c85767ccc8        bitwarden/web:1.27.0           "/entrypoint.sh"    4 minutes ago       Up 4 minutes        5000/tcp                         bitwarden-1-web
0ed334f899e4        bitwarden/icons:1.20.0         "/entrypoint.sh"    4 minutes ago       Up 4 minutes        5000/tcp                         bitwarden-1-icons
a5003d6a3242        bitwarden/nginx:1.20.0         "/entrypoint.sh"    4 minutes ago       Up 3 minutes        80/tcp, 0.0.0.0:1024->8443/tcp   bitwarden-1-nginx
2403010a6f76        bitwarden/attachments:1.20.0   "/entrypoint.sh"    4 minutes ago       Up 4 minutes        5000/tcp                         bitwarden-1-attachments
f1cfa0256e37        bitwarden/identity:1.20.0      "/entrypoint.sh"    4 minutes ago       Up 4 minutes        5000/tcp                         bitwarden-identity
6a534b69ee3c        bitwarden/icons:1.20.0         "/entrypoint.sh"    4 minutes ago       Up 4 minutes        5000/tcp                         bitwarden-icons
44b85724e1a9        bitwarden/admin:1.20.0         "/entrypoint.sh"    4 minutes ago       Up 4 minutes        5000/tcp                         bitwarden-admin
3b85789ec828        bitwarden/web:1.27.0           "/entrypoint.sh"    4 minutes ago       Up 4 minutes        5000/tcp                         bitwarden-web
8b78298e8b0c        bitwarden/api:1.20.0           "/entrypoint.sh"    4 minutes ago       Up 4 minutes        5000/tcp                         bitwarden-api
de2cc31de8fe        bitwarden/nginx:1.20.0         "/entrypoint.sh"    4 minutes ago       Up 4 minutes        80/tcp, 0.0.0.0:1025->8443/tcp   bitwarden-nginx
25d7c882094b        bitwarden/attachments:1.20.0   "/entrypoint.sh"    4 minutes ago       Up 4 minutes        5000/tcp                         bitwarden-attachments
4b4490e15c42        bitwarden/mssql:1.20.0         "/entrypoint.sh"    4 minutes ago       Up 4 minutes        1433/tcp                         bitwarden-1-mssql
5ff0d0ae9002        bitwarden/mssql:1.20.0         "/entrypoint.sh"    4 minutes ago       Up 4 minutes        1433/tcp                         bitwarden-mssql
```

**Comment by Mart124** [comment]
Closing this for now as there should be a better way to achieve this in the future.

**Pull request closed without merging**
